language: rust
rust:
- stable
cache: cargo
install:
- curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f
script:
- cd math
- wasm-pack build --target web
- rm -r target
- cd ..
deploy:
  provider: s3
  access_key_id: AKIAZLEFFN65T3RR3BJB
  secret_access_key:
    secure: $AWS_SECRET_KEY
  bucket: calc.sunado.bid
  acl: 'public_read_write'
  on:
    repo: sunado/CalcWasm
  skip_cleanup: 'true'
  region: ap-northeast-1